Grafana + Prometheus (HW1)
PetrovitchSharp/recsys-2023 pull request #1
Opened 2023-04-09 16:08 UTC by PetrovitchSharp

Added prometheus + grafana

### Prometheus

![Screenshot from 2023-04-09 17-28-43](https://user-images.githubusercontent.com/58230283/230783673-b0b8fc3c-bd86-4ef8-a07a-775c206fa655.png)

### Grafana

![Screenshot from 2023-04-09 14-42-41](https://user-images.githubusercontent.com/58230283/230783676-49d05eaf-6450-4efc-ab41-63bd4c25d222.png)

![Screenshot from 2023-04-09 14-39-21](https://user-images.githubusercontent.com/58230283/230783680-07982cba-9839-4756-9505-bc4adaa28042.png)

2023-04-10 13:34 UTC, feldlime approved these changes

2023-04-10 13:34 UTC, feldlime commented on .dockerignore
> -*
За что так с этим файлом?

2023-04-10 13:34 UTC, feldlime commented on requirements.txt
Зачем requirements.txt одновременно с поетри?

2023-04-10 13:34 UTC, feldlime commented on requirements.txt
Да еще и такой страшный

2023-04-10 13:34 UTC, feldlime commented on Dockerfile
> -RUN pip install -U --no-cache-dir pip poetry setuptools wheel && \
А с этим файлом что?

2023-04-10 13:34 UTC, feldlime commented on docker-compose.yaml
> +    driver: bridge
newline

2023-04-10 13:34 UTC, feldlime commented on docker-compose.yaml
> +        ipv4_address: 172.16.238.10
что это за адрес, зачем его фиксировать в гите?

2023-04-10 13:34 UTC, feldlime commented on prometheus.yml
> +      - targets: ["app:8000"]
newline

2023-04-11 05:51 UTC, feldlime requested changes

2023-04-11 05:51 UTC, feldlime commented on service/data/dataset/prepared_featured_users_full.csv
> +id,value,feature
для чего нужны эти csv файлы?

2023-04-11 05:51 UTC, feldlime commented on Makefile
> +.venv: requirements.txt
requirements.txt - неудачный пререквизит, не стоит его указывать

Если его нет, команда должна упасть, а здесь она просто не выполнится

2023-04-11 05:51 UTC, feldlime commented on Makefile
> -lint: isort flake mypy pylint
ну уж нет, давайте ка вернем pylint, я не готов все замечания вместо него руками писать :)

2023-04-11 16:14 UTC, PetrovitchSharp commented on service/data/dataset/prepared_featured_users_full.csv
> +id,value,feature
Это mock файлы, если можно так выразиться. Небольше реалистичные заглушки. Нужны чтобы тесты проходились, ибо есть conftest, который создает экземпляр приложения, а при создании экземпляра приложения грузятся модели и данные к ним (чтобы на лету не грузить по миллиону лет csv'шники). Ну и тесты, соответственно, без заглушек валятся

2023-04-11 16:52 UTC, PetrovitchSharp commented on Makefile
> +.venv: requirements.txt
убрал

2023-04-11 16:52 UTC, PetrovitchSharp commented on Makefile
> -lint: isort flake mypy pylint
Вернул pylint

2023-04-12 02:39 UTC, feldlime commented on service/data/dataset/prepared_featured_users_full.csv
> +id,value,feature
тогда лучше положить все это начиная с папки data в папку tests, и сразу станет понятно что к чему

2023-04-12 09:52 UTC, PetrovitchSharp commented on service/data/dataset/prepared_featured_users_full.csv
> +id,value,feature
Там надо будет очень много где менять в целом конфигурацию. Я попробовал разделить test и prod конфигурацию "красиво и элегантно", но все к чертям сломалось спустя 3 часа попыток заставить все работать как надо и я понял, что лучше оставить как есть (можно конечно костыли понаставить...). Да, будь оно в tests, было бы нагляднее, но и так можно это интерпретировать как образец данных. Короче говоря издержки архитектуры, построенной в прошлом семестре, слишком связанный код местами получился

2023-04-12 11:32 UTC, feldlime commented on service/data/dataset/prepared_featured_users_full.csv
> +id,value,feature
звучит как вода

не понимаю в чем проблема поменять путь к данным

так не приму

2023-04-12 11:41 UTC, feldlime requested changes

2023-04-12 11:41 UTC, feldlime commented on ci-requirements.txt
> +astroid==2.15.2
должны быть только либы, которые импортируются явно либо необходимы, но явно не устанавливаются

из этого файла можно удалить примерно половино

2023-04-12 11:41 UTC, feldlime commented on requirements.txt
> +anyio==3.6.2
аналогично здесь

2023-04-12 11:41 UTC, feldlime commented on service/api/views.py
> +    if model_name not in predictors_list:
сначала проверка что модель в списке (за `O(n)`, кстати, - вообще непонятно зачем вытаскивать ключи, можно же просто `if model_name not in predictors`, тогда будет `O(1)`), а потом на 54 строчке снова извлечение из словаря `predictors[model_name]`

мало того что 2 раза, так это еще и не питоник вэй

лучше
```
try:
    model = predictors[model_name]
except KeyError:
    raise ModelNotFoundError...

reco = model.recommend...
```

2023-04-12 13:44 UTC, PetrovitchSharp commented on service/data/dataset/prepared_featured_users_full.csv
> +id,value,feature
Как говорил классик "Нельзя просто так взять и поменять пути к данным") Пришлось налепить дополнительный проброс конфига почти сквозь все приложение. Как я и говорил - архитектура, построенная в прошлом семестре, не давала просто взять и поменять в одном месте пути. Но теперь вроде все работает

2023-04-12 13:45 UTC, PetrovitchSharp commented on ci-requirements.txt
> +astroid==2.15.2
поправил

2023-04-12 13:45 UTC, PetrovitchSharp commented on requirements.txt
> +anyio==3.6.2
поправил

2023-04-12 13:45 UTC, PetrovitchSharp commented on service/api/views.py
> +    if model_name not in predictors_list:
поправил

2023-04-13 02:39 UTC, feldlime requested changes

2023-04-13 02:39 UTC, feldlime commented on Makefile
> +	flake8 --max-line-length 120 $(PROJECT) $(TESTS)
для этих настроек есть setup.cfg

и mypy там же

2023-04-13 02:39 UTC, feldlime commented on data/.gitkeep
кажется теперь это можно убрать

2023-04-13 02:39 UTC, feldlime commented on service/api/views.py
> +    @router.get(path="/health", tags=["Health"], response_model=HealthResponse)
плохая идея засовывать views внутрь одной большой функи

в данном случае все можно сделать лучше и проще: 

при создании приложения в `app.py` нужно просто добавить либо `config` целиком, либо `predictors` в `app.state` по аналогии с `k_recs` и он будет доступен в запросе как `request.app.state.config/predictors`

2023-04-13 02:39 UTC, feldlime commented on service/settings.py
> +            predictors_path=os.path.join(root_path, "tests/mock_data/predictors"),
нет, ни в коем случае!

тесты знают про сервис, сервис про тесты не знает - сервис не должен зависеть от тестов и не должен под них подстраиваться, то что нужно для тестов должно быть только в тестах!

в данном случае есть 2 варианта:
1. (проще) в `contest.py` в `service_config` вместо вызова `get_config` создать конфиг с нужными путями напрямую (как здесь, только не здесь, а там)
2. (правильнее) управлять ситуацией через энвы, как и должно быть. Для этого в `contest.py` нужно сделать следующее
```
from _pytest.monkeypatch import MonkeyPatch

@pytest.fixture
def set_env() -> tp.Iterator[None]:
    monkeypatch = MonkeyPatch()
    monkeypatch.setenv("PREDICTORS_PATH", os.path.join(root_path, "tests/mock_data/predictors"))
    # аналогично остальные

    yield

    monkeypatch.undo()


@pytest.fixture
def service_config(set_env: None) -> ServiceConfig:
    return get_config()
```

И в любом случае никакой `ApplicationMode` уже не нужен

2023-04-14 12:31 UTC, PetrovitchSharp commented on Makefile
> +	flake8 --max-line-length 120 $(PROJECT) $(TESTS)
исправлено

2023-04-14 12:31 UTC, PetrovitchSharp commented on data/.gitkeep
убрано

2023-04-14 12:32 UTC, PetrovitchSharp commented on service/api/views.py
> +    @router.get(path="/health", tags=["Health"], response_model=HealthResponse)
возвращено к изначальному виду

2023-04-14 12:32 UTC, PetrovitchSharp commented on service/settings.py
> +            predictors_path=os.path.join(root_path, "tests/mock_data/predictors"),
через адскую боль и страдания вроде бы исправлено

2023-04-18 08:18 UTC, PetrovitchSharp commented
Prometheus: 

![image](https://user-images.githubusercontent.com/58230283/232715442-368f862a-8501-406a-ade3-fd4323c8f65f.png)

Grafana: 

![image](https://user-images.githubusercontent.com/58230283/232715549-8076e85b-711d-42a6-84a7-268e8a08be1c.png)

Response Time:

![image](https://user-images.githubusercontent.com/58230283/232715589-f2f44861-0b6f-4f42-a7b4-c5404fa276a0.png)

Memory Usage:

![image](https://user-images.githubusercontent.com/58230283/232715625-c8c7b490-6dde-454a-82ed-521d837f91d8.png)

CPU Usage:

![image](https://user-images.githubusercontent.com/58230283/232716066-3540e789-3767-4988-b306-4e9a699fb827.png)

RPS:

![image](https://user-images.githubusercontent.com/58230283/232716176-8323b3fe-4ef1-4c26-bc1d-d421aceb161a.png)

2023-04-18 08:30 UTC, feldlime approved these changes

2023-04-18 08:30 UTC, feldlime commented on service/predictors/random.py
>          reco = random.sample(range(1000), self.k_recs)
1. Хардкодить - плохо
2. Почему 1000 непонятно

2023-04-19 09:09 UTC, merged